POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QxMjMiLCJpZCI6IjYzMDY2YzYyZmVkZGUyYWNiZDNkMTZlMCIsImlhdCI6MTY2MjAzMzYzMX0.5CDuXnQh42TymVxBP2a8-K5EzVeB_poVDJCYztqlNEs

{
    "title": "Testing blog...4",
    "author": "Test Author4",
    "url": "http://www.google.com",
    "likes": 100
}