DELETE http://localhost:3003/api/blogs/63066ca1fedde2acbd3d16e6
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QxMjMiLCJpZCI6IjYzMDY2YzYyZmVkZGUyYWNiZDNkMTZlMCIsImlhdCI6MTY2MTQ4NzA2N30.0YPBGbNb64c8rtMzYPq9DK29ta1_CtY5g1sxuCD1lac